Верстка формы
htmlacademy-adaptive/1651395-pognali-22 pull request #3
Opened 2021-03-30 11:26 UTC by Kettel1

2021-03-31 07:22 UTC, Dima-Dim requested changes

2021-03-31 07:22 UTC, Dima-Dim commented on source/form.html
> +        <h2 class='step-1__title'>Шаг 1.</h2>
h2 по уровню выше, значит тут h2.

2021-03-31 07:22 UTC, Dima-Dim commented on source/form.html
> +        <h2 class='step-1__title'>Даты пребывания</h2>
Либо это в одном h3, либо уже не h.

2021-03-31 07:22 UTC, Dima-Dim commented on source/form.html
> +        <p class='user-info__hashtags' class=''>#бургер #бар #футбол #концерт #крафт</p>
Два атрибута class.
Ну забываем про https://validator.w3.org/nu/

2021-03-31 07:22 UTC, Dima-Dim commented on source/form.html
> +    <a class='page-header__logo'>
Элемент `page-header__logo` вне блока `page-header`

2021-03-31 07:22 UTC, Dima-Dim commented on source/form.html
> +          <ul class='calendar-days__list'>
Элемент `calendar-days__list` вне блока `calendar-days`

2021-03-31 13:07 UTC, Kettel1 commented on source/form.html
> +        <h2 class='step-1__title'>Шаг 1.</h2>
Поправил блок блок

2021-03-31 13:17 UTC, Kettel1 commented on source/form.html
> +          <ul class='calendar-days__list'>
calendar-day это как отдельный блок идет, а так нельзя? я просто разеделение дефисом сделал, говорили что блок в блок можно вкладывать

2021-04-01 06:54 UTC, Dima-Dim requested changes
Элемент nav__list вне блока nav
Элемент nav__login вне блока nav
Элемент nav__login вне блока nav
Что такое registration_question и address_wrapper?
Элемент page-footer__button и page-footer__background вне блока page-footer

2021-04-01 06:54 UTC, Dima-Dim commented on source/catalog.html
> +      <button class='form-nav__login button__login'>Авторизация</button>
Элемент button__login вне блока button

2021-04-01 06:54 UTC, Dima-Dim commented on source/form.html
> +          <ul class='calendar-days__list'>
Блок в блок можно. В этом случае где у нас блок calendar-days?

2021-04-01 17:41 UTC, merged