Самая базовая стилизация index.html, базовее некуда
htmlacademy-adaptive/1651395-pognali-22 pull request #5
Opened 2021-04-04 14:41 UTC by Kettel1

Вот прям совсем "чуть чуть" накидал на скорую руку))))))))) я пока верстаю под 320px решил поубирать элементы не относящиеся к этому разрешению, потом буду добавлять по мере верстки

2021-04-04 14:48 UTC, Kettel1 commented
Смотреть исключительно на разрешении 320px :)

2021-04-05 05:11 UTC, Dima-Dim requested changes
И что случилось с package-lock.json? Он как-то сильно похудел.

2021-04-05 05:11 UTC, Dima-Dim commented on source/sass/about-service.scss
> +  font-family: "BloggerSans", sans-serif;
https://up.htmlacademy.ru/adaptive/22/criteries#b10

2021-04-05 05:11 UTC, Dima-Dim commented on source/sass/cards-country.scss
> +  opacity: .5
Лучше писать по человечески 0.5, читать и понимать будет проще.

2021-04-05 05:11 UTC, Dima-Dim commented on source/sass/footer-social.scss
> +    background-image: url("../img/logo_html 1.svg");
`logo_html 1.svg` серьёзно? :) а что не `logo html 1.svg` :)))

2021-04-05 05:11 UTC, Dima-Dim commented on source/sass/main-nav.scss
> +.header-content {
Всё что про header-content должно быть в файле header-content.scss

2021-04-05 05:11 UTC, Dima-Dim commented on source/sass/registration.scss
> +.registration-social {
`registration` и `registration-social` тоже разные блоки и должны быть в разных файлах

2021-04-05 05:11 UTC, Dima-Dim commented on source/sass/style.scss
> +@font-face {
Шрифты в файл fonts.scss

2021-04-05 05:11 UTC, Dima-Dim commented on source/sass/style.scss
> +//Colors
Переменные в файл с переменными и он обычно идёт первым при подключении.

2021-04-05 05:11 UTC, Dima-Dim commented on source/sass/style.scss
> +body {
Тоже вынести в какой-то отдельный файл.

2021-04-05 05:11 UTC, Dima-Dim commented on source/sass/style.scss
> +.visually-hidden {
Тоже отдельный блок - отдельный файл.

2021-04-05 05:11 UTC, Dima-Dim commented on source/sass/style.scss
> +.container {
и так далее.

2021-04-05 05:11 UTC, Dima-Dim commented on source/sass/style.scss
> +.big-button {
Мне кажется или название напоминает модификатор?

2021-04-06 02:13 UTC, Kettel1 commented on source/sass/footer-social.scss
> +    background-image: url("../img/logo_html 1.svg");
я в фигме просто выгружал названия, не менял их)

2021-04-06 10:57 UTC, Dima-Dim requested changes

2021-04-06 10:57 UTC, Dima-Dim commented on source/index.html
> +          <img src='img/logo_mobile-git ad3.png' alt='logo'>
Всё ещё есть пробелы.
https://validator.w3.org/nu/

2021-04-29 05:42 UTC, Dima-Dim requested changes
logo_html 1.svg и logo_mobile 2.png и т.п. не нужно использовать пробелы в названиях файлов.

2021-04-29 05:42 UTC, Dima-Dim commented on source/catalog.html
> +        <a class="tabs__button catalog-button" href='#'>Показать</a>
Кажется `tabs__button` не в блоке `tabs`

2021-05-21 06:24 UTC, merged